// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id HwIfAddDelHook -d Package=vnet -d DepsType=HwIfAddDelHookVec -d Type=HwIfAddDelHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/elib/dep"
)

type HwIfAddDelHookVec struct {
	deps  dep.Deps
	hooks []HwIfAddDelHook
}

func (t *HwIfAddDelHookVec) Len() int {
	return t.deps.Len()
}

func (t *HwIfAddDelHookVec) Get(i int) HwIfAddDelHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *HwIfAddDelHookVec) Add(x HwIfAddDelHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
