// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id ifThread -d VecType=ifThreadVec -d Type=*InterfaceThread github.com/platinasystems/elib/vec.tmpl]

package vnet

import (
	"github.com/platinasystems/elib"
)

type ifThreadVec []*InterfaceThread

func (p *ifThreadVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*InterfaceThread, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *ifThreadVec) validate(i uint, zero **InterfaceThread) **InterfaceThread {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*InterfaceThread, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *ifThreadVec) Validate(i uint) **InterfaceThread {
	return p.validate(i, (**InterfaceThread)(nil))
}
func (p *ifThreadVec) ValidateInit(i uint, zero *InterfaceThread) **InterfaceThread {
	return p.validate(i, &zero)
}

func (p ifThreadVec) Len() uint { return uint(len(p)) }
