// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id initHook -d Package=vnet -d DepsType=initHookVec -d Type=initHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/elib/dep"
)

type initHookVec struct {
	deps  dep.Deps
	hooks []initHook
}

func (t *initHookVec) Len() int {
	return t.deps.Len()
}

func (t *initHookVec) Get(i int) initHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *initHookVec) Add(x initHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
