// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id SwIfAddDelHook -d Package=vnet -d DepsType=SwIfAddDelHookVec -d Type=SwIfAddDelHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/elib/dep"
)

type SwIfAddDelHookVec struct {
	deps  dep.Deps
	hooks []SwIfAddDelHook
}

func (t *SwIfAddDelHookVec) Len() int {
	return t.deps.Len()
}

func (t *SwIfAddDelHookVec) Get(i int) SwIfAddDelHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *SwIfAddDelHookVec) Add(x SwIfAddDelHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
