// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id RefVecIn -d VecType=RefVecInVec -d Type=*RefVecIn github.com/platinasystems/elib/vec.tmpl]

package vnet

import (
	"github.com/platinasystems/elib"
)

type RefVecInVec []*RefVecIn

func (p *RefVecInVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*RefVecIn, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *RefVecInVec) validate(i uint, zero **RefVecIn) **RefVecIn {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*RefVecIn, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *RefVecInVec) Validate(i uint) **RefVecIn                     { return p.validate(i, (**RefVecIn)(nil)) }
func (p *RefVecInVec) ValidateInit(i uint, zero *RefVecIn) **RefVecIn { return p.validate(i, &zero) }

func (p RefVecInVec) Len() uint { return uint(len(p)) }
