// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id errorThread -d VecType=errorThreadVec -d Type=*errorThread github.com/platinasystems/elib/vec.tmpl]

package vnet

import (
	"github.com/platinasystems/elib"
)

type errorThreadVec []*errorThread

func (p *errorThreadVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*errorThread, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *errorThreadVec) validate(i uint, zero **errorThread) **errorThread {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*errorThread, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *errorThreadVec) Validate(i uint) **errorThread { return p.validate(i, (**errorThread)(nil)) }
func (p *errorThreadVec) ValidateInit(i uint, zero *errorThread) **errorThread {
	return p.validate(i, &zero)
}

func (p errorThreadVec) Len() uint { return uint(len(p)) }
