// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id interfaceNodeThreadVec -d VecType=interfaceNodeThreadVec -d Type=*interfaceNodeThread github.com/platinasystems/elib/vec.tmpl]

package vnet

import (
	"github.com/platinasystems/elib"
)

type interfaceNodeThreadVec []*interfaceNodeThread

func (p *interfaceNodeThreadVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*interfaceNodeThread, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *interfaceNodeThreadVec) validate(new_len uint, zero **interfaceNodeThread) **interfaceNodeThread {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *interfaceNodeThreadVec) validateSlowPath(zero **interfaceNodeThread,
	c, l, lʹ elib.Index) **interfaceNodeThread {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*interfaceNodeThread, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *interfaceNodeThreadVec) Validate(i uint) **interfaceNodeThread {
	return p.validate(i+1, (**interfaceNodeThread)(nil))
}

func (p *interfaceNodeThreadVec) ValidateInit(i uint, zero *interfaceNodeThread) **interfaceNodeThread {
	return p.validate(i+1, &zero)
}

func (p *interfaceNodeThreadVec) ValidateLen(l uint) (v **interfaceNodeThread) {
	if l > 0 {
		v = p.validate(l, (**interfaceNodeThread)(nil))
	}
	return
}

func (p *interfaceNodeThreadVec) ValidateLenInit(l uint, zero *interfaceNodeThread) (v **interfaceNodeThread) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p interfaceNodeThreadVec) Len() uint { return uint(len(p)) }
