// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id Ref -d VecType=RefVec -d Type=Ref github.com/platinasystems/elib/vec.tmpl]

package vnet

import (
	"github.com/platinasystems/elib"
)

type RefVec []Ref

func (p *RefVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Ref, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *RefVec) validate(i uint, zero *Ref) *Ref {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Ref, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *RefVec) Validate(i uint) *Ref               { return p.validate(i, (*Ref)(nil)) }
func (p *RefVec) ValidateInit(i uint, zero Ref) *Ref { return p.validate(i, &zero) }

func (p RefVec) Len() uint { return uint(len(p)) }
