// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id HwIfSetSpeedHook -d Package=vnet -d DepsType=HwIfSetSpeedHookVec -d Type=HwIfSetSpeedHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/elib/dep"
)

type HwIfSetSpeedHookVec struct {
	deps  dep.Deps
	hooks []HwIfSetSpeedHook
}

func (t *HwIfSetSpeedHookVec) Len() int {
	return t.deps.Len()
}

func (t *HwIfSetSpeedHookVec) Get(i int) HwIfSetSpeedHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *HwIfSetSpeedHookVec) Add(x HwIfSetSpeedHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
