// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=rpc -id inputEvent -d Type=inputEvent github.com/platinasystems/elib/elog/event.tmpl]

package rpc

import (
	"fmt"
	. "github.com/platinasystems/elib/elog"
	"unsafe"
)

var inputEventType = &EventType{}

func init() {
	inputEventType.Stringer = func(e *Event) string {
		x := (*inputEvent)(unsafe.Pointer(&e.Data[0]))
		return x.String()
	}
}

func inputEventNew() (x *inputEvent) {
	e := Add(inputEventType)
	if unsafe.Sizeof(*x) > unsafe.Sizeof(e.Data) {
		panic(fmt.Sprintf("type too large: inputEvent %d bytes", unsafe.Sizeof(*x)))
	}
	x = (*inputEvent)(unsafe.Pointer(&e.Data[0]))
	return
}

func (x inputEvent) Log() {
	p := inputEventNew()
	*p = x
}

func (x *inputEvent) Event() (e *Event) {
	e = (*Event)(unsafe.Pointer(uintptr(unsafe.Pointer(x)) - unsafe.Offsetof(e.Data)))
	return
}

func (x *inputEvent) LogEventString(l *Log) string {
	e := x.Event()
	return fmt.Sprintf("%s: %s", e.EventString(l), x)
}

func (x *inputEvent) EventString() string { return x.LogEventString(DefaultLog) }
