// generated by stringer -type=Type; DO NOT EDIT

package ethernet

import "fmt"

const _Type_name = "LLC_LENGTHIP4ARPVINES_IPVINES_LOOPBACKVINES_ECHOTRAINCDPCGMPSRP_CONTROLCENTRINO_PROMISCDECNETDECNET_DUMP_LOADDECNET_REMOTE_CONSOLEDECNET_ROUTEDEC_LATDEC_DIAGNOSTICDEC_CUSTOMERDEC_SCATRANSPARENT_BRIDGINGRAW_FRAME_RELAYREVERSE_ARPDEC_LAN_BRIDGEDEC_ETHERNET_ENCRYPTIONDEC_LAN_TRAFFIC_MONITORDEC_LASTAPPLETALKIBM_SNAAPPLETALK_AARPWELLFLEET_COMPRESSIONVLANIPXSNMPCABLETRON_ISMPCABLETRON_ISMP_TBFLOODIP6ATOMICTCP_IP_COMPRESSIONIP_AUTONOMOUS_SYSTEMSSECURE_DATAMAC_CONTROLSLOW_PROTOCOLSPPPMPLS_UNICASTMPLS_MULTICASTPPPOE_DISCOVERYPPPOE_SESSIONINTEL_ANSMICROSOFT_NLB_HEARTBEATCDMA_2000PROFINETHYPERSCSIAOEBRDWALKLOOPBACKRTNET_MACRTNET_CONFIGVLAN_IN_VLANPGLANSRP_ISISRESERVED"

var _Type_map = map[Type]string{
	1536:  _Type_name[0:10],
	2048:  _Type_name[10:13],
	2054:  _Type_name[13:16],
	2989:  _Type_name[16:24],
	2990:  _Type_name[24:38],
	2991:  _Type_name[38:48],
	6532:  _Type_name[48:53],
	8192:  _Type_name[53:56],
	8193:  _Type_name[56:60],
	8199:  _Type_name[60:71],
	9298:  _Type_name[71:87],
	24576: _Type_name[87:93],
	24577: _Type_name[93:109],
	24578: _Type_name[109:130],
	24579: _Type_name[130:142],
	24580: _Type_name[142:149],
	24581: _Type_name[149:163],
	24582: _Type_name[163:175],
	24583: _Type_name[175:182],
	25944: _Type_name[182:202],
	25945: _Type_name[202:217],
	32821: _Type_name[217:228],
	32824: _Type_name[228:242],
	32829: _Type_name[242:265],
	32831: _Type_name[265:288],
	32833: _Type_name[288:296],
	32923: _Type_name[296:305],
	32981: _Type_name[305:312],
	33011: _Type_name[312:326],
	33023: _Type_name[326:347],
	33024: _Type_name[347:351],
	33079: _Type_name[351:354],
	33100: _Type_name[354:358],
	33277: _Type_name[358:372],
	33279: _Type_name[372:394],
	34525: _Type_name[394:397],
	34527: _Type_name[397:403],
	34667: _Type_name[403:421],
	34668: _Type_name[421:442],
	34669: _Type_name[442:453],
	34824: _Type_name[453:464],
	34825: _Type_name[464:478],
	34827: _Type_name[478:481],
	34887: _Type_name[481:493],
	34888: _Type_name[493:507],
	34915: _Type_name[507:522],
	34916: _Type_name[522:535],
	34925: _Type_name[535:544],
	34927: _Type_name[544:567],
	34945: _Type_name[567:576],
	34962: _Type_name[576:584],
	34970: _Type_name[584:593],
	34978: _Type_name[593:596],
	34990: _Type_name[596:603],
	36864: _Type_name[603:611],
	36897: _Type_name[611:620],
	36898: _Type_name[620:632],
	37120: _Type_name[632:644],
	39321: _Type_name[644:649],
	65278: _Type_name[649:657],
	65535: _Type_name[657:665],
}

func (i Type) String() string {
	if str, ok := _Type_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Type(%d)", i)
}
