// generated by stringer -type=Type; DO NOT EDIT

package ethernet

import "fmt"

const (
	_Type_name_0 = "IP4"
	_Type_name_1 = "ARP"
	_Type_name_2 = "VLAN"
	_Type_name_3 = "IP6"
)

var (
	_Type_index_0 = [...]uint8{0, 3}
	_Type_index_1 = [...]uint8{0, 3}
	_Type_index_2 = [...]uint8{0, 4}
	_Type_index_3 = [...]uint8{0, 3}
)

func (i Type) String() string {
	switch {
	case i == 2048:
		return _Type_name_0
	case i == 2054:
		return _Type_name_1
	case i == 33024:
		return _Type_name_2
	case i == 34525:
		return _Type_name_3
	default:
		return fmt.Sprintf("Type(%d)", i)
	}
}
