// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=main -id ReqEvent -d Type=reqEvent github.com/platinasystems/elib/elog/event.tmpl]

package main

import (
	. "github.com/platinasystems/elib/elog"
)

var reqEventType = &EventType{
	Name: "main.reqEvent",
}

func init() {
	t := reqEventType
	t.Stringer = stringer_reqEvent
	t.Encode = encode_reqEvent
	t.Decode = decode_reqEvent
	RegisterType(reqEventType)
}

func stringer_reqEvent(e *Event) string {
	var x reqEvent
	x.Decode(e.Data[:])
	return x.String()
}

func encode_reqEvent(b []byte, e *Event) int {
	var x reqEvent
	x.Decode(e.Data[:])
	return x.Encode(b)
}

func decode_reqEvent(b []byte, e *Event) int {
	var x reqEvent
	x.Decode(b)
	return x.Encode(e.Data[:])
}

func (x reqEvent) Log() {
	e := Add(reqEventType)
	x.Encode(e.Data[:])
}
