// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=srpc -id inputEvent -d Type=inputEvent github.com/platinasystems/elib/elog/event.tmpl]

package srpc

import (
	. "github.com/platinasystems/elib/elog"
)

var inputEventType = &EventType{
	Name: "srpc.inputEvent",
}

func init() {
	t := inputEventType
	t.Stringer = stringer_inputEvent
	t.Encode = encode_inputEvent
	t.Decode = decode_inputEvent
	RegisterType(inputEventType)
}

func stringer_inputEvent(e *Event) string {
	var x inputEvent
	x.Decode(e.Data[:])
	return x.String()
}

func encode_inputEvent(b []byte, e *Event) int {
	var x inputEvent
	x.Decode(e.Data[:])
	return x.Encode(b)
}

func decode_inputEvent(b []byte, e *Event) int {
	var x inputEvent
	x.Decode(b)
	return x.Encode(e.Data[:])
}

func (x inputEvent) Log() {
	e := Add(inputEventType)
	x.Encode(e.Data[:])
}
