// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ixge -id rx_dma_queue -d VecType=rx_dma_queue_vec -d Type=rx_dma_queue github.com/platinasystems/elib/vec.tmpl]

package ixge

import (
	"github.com/platinasystems/elib"
)

type rx_dma_queue_vec []rx_dma_queue

func (p *rx_dma_queue_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]rx_dma_queue, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *rx_dma_queue_vec) validate(i uint, zero *rx_dma_queue) *rx_dma_queue {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]rx_dma_queue, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *rx_dma_queue_vec) Validate(i uint) *rx_dma_queue { return p.validate(i, (*rx_dma_queue)(nil)) }
func (p *rx_dma_queue_vec) ValidateInit(i uint, zero rx_dma_queue) *rx_dma_queue {
	return p.validate(i, &zero)
}

func (p rx_dma_queue_vec) Len() uint { return uint(len(p)) }
