// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ixge -id rx_from_hw_descriptor -d Type=rx_from_hw_descriptor -d VecType=rx_from_hw_descriptor_vec github.com/platinasystems/elib/hw/dma_mem.tmpl]

package ixge

import (
	"github.com/platinasystems/elib"
	"github.com/platinasystems/elib/hw"

	"reflect"
	"unsafe"
)

type rx_from_hw_descriptor_vec []rx_from_hw_descriptor

func fromByteSlice_rx_from_hw_descriptor(b []byte, l, c int) (x rx_from_hw_descriptor_vec) {
	s := int(unsafe.Sizeof(x[0]))
	if l == 0 {
		l = len(b) / s
		c = cap(b)
	}
	return *(*rx_from_hw_descriptor_vec)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&b[0])),
		Len:  l,
		Cap:  c / s,
	}))
}

func (x rx_from_hw_descriptor_vec) toByteSlice() []byte {
	l := len(x)
	s := unsafe.Sizeof(x[0])
	l *= int(s)
	return *(*[]byte)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&x[0])),
		Len:  l,
		Cap:  l}))
}

func rx_from_hw_descriptorAlloc(n int) (x rx_from_hw_descriptor_vec, id elib.Index) {
	var b []byte
	var c uint
	b, id, _, c = hw.DmaAlloc(uint(n) * uint(unsafe.Sizeof(x[0])))
	x = fromByteSlice_rx_from_hw_descriptor(b, n, int(c))
	return
}

func rx_from_hw_descriptorNew() (x rx_from_hw_descriptor_vec, id elib.Index) {
	return rx_from_hw_descriptorAlloc(1)
}

func (x *rx_from_hw_descriptor_vec) Free(id elib.Index) {
	hw.DmaFree(id)
	*x = nil
}

func (x *rx_from_hw_descriptor_vec) Get(id elib.Index) {
	*x = fromByteSlice_rx_from_hw_descriptor(hw.DmaGet(id), 0, 0)
}

func (x *rx_from_hw_descriptor) PhysAddress() uintptr {
	return hw.DmaPhysAddress(uintptr(unsafe.Pointer(x)))
}
