// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id ifAddr -d VecType=ifAddrVec -d Type=ifAddr github.com/platinasystems/elib/vec.tmpl]

package ip

import (
	"github.com/platinasystems/elib"
)

type ifAddrVec []ifAddr

func (p *ifAddrVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]ifAddr, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *ifAddrVec) Validate(i uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]ifAddr, l, c)
		copy(q, *p)
		*p = q
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
}

func (p ifAddrVec) Len() uint { return uint(len(p)) }
