// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id AdjVec -d VecType=AdjVec -d Type=Adj github.com/platinasystems/elib/vec.tmpl]

package ip

import (
	"github.com/platinasystems/elib"
)

type AdjVec []Adj

func (p *AdjVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Adj, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *AdjVec) Validate(i uint) *Adj {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Adj, l, c)
		copy(q, *p)
		*p = q
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}

func (p AdjVec) Len() uint { return uint(len(p)) }
