// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id AdjRemapVec -d VecType=AdjRemapVec -d Type=AdjRemap github.com/platinasystems/elib/vec.tmpl]

package ip

import (
	"github.com/platinasystems/elib"
)

type AdjRemapVec []AdjRemap

func (p *AdjRemapVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]AdjRemap, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *AdjRemapVec) validate(i uint, zero *AdjRemap) *AdjRemap {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]AdjRemap, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *AdjRemapVec) Validate(i uint) *AdjRemap                    { return p.validate(i, (*AdjRemap)(nil)) }
func (p *AdjRemapVec) ValidateInit(i uint, zero AdjRemap) *AdjRemap { return p.validate(i, &zero) }

func (p AdjRemapVec) Len() uint { return uint(len(p)) }
