// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id adjAddDelHook -d Package=ip -d DepsType=adjAddDelHookVec -d Type=adjAddDelHook -d Data=adjAddDelHooks github.com/platinasystems/elib/dep/dep.tmpl]

package ip

import (
	"github.com/platinasystems/elib/dep"
)

type adjAddDelHookVec struct {
	deps           dep.Deps
	adjAddDelHooks []adjAddDelHook
}

func (t *adjAddDelHookVec) Len() int {
	return t.deps.Len()
}

func (t *adjAddDelHookVec) Get(i int) adjAddDelHook {
	return t.adjAddDelHooks[t.deps.Index(i)]
}

func (t *adjAddDelHookVec) Add(x adjAddDelHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.adjAddDelHooks = append(t.adjAddDelHooks, x)
}
