// generated by stringer -type=Protocol; DO NOT EDIT

package ip

import "fmt"

const (
	_Protocol_name_0 = "IP6_HOP_BY_HOP_OPTIONSICMPIGMPGGPIP_IN_IPSTTCPCBTEGPIGPBBN_RCC_MONNVP_IIPUPARGUSEMCONXNETCHAOSUDPMUXDCN_MEASHMPPRMXNS_IDPTRUNK_1TRUNK_2LEAF_1LEAF_2RDPIRTPISO_TP4NETBLTMFE_NSPMERIT_INPSEP_3PCIDPRXTPDDPIDPR_CMTPTPILIP6_IN_IPSDRPIPV6_ROUTEIPV6_FRAGMENTATIONIDRPRSVPGREMHRPBNAIPSEC_ESPIPSEC_AHI_NLSPSWIPENARPMOBILETLSPSKIPICMP6IP6_NONXTIP6_DESTINATION_OPTIONS"
	_Protocol_name_1 = "CFTP"
	_Protocol_name_2 = "SAT_EXPAKKRYPTOLANRVDIPPC"
	_Protocol_name_3 = "SAT_MONVISAIPCVCPNXCPHBWSNPVPBR_SAT_MONSUN_NDWB_MONWB_EXPAKISO_IPVMTPSECURE_VMTPVINESTTPNSFNET_IGPDGPTCFEIGRPOSPFSPRITE_RPCLARPMTPAXIPIPMICPSCC_SPETHERIPENCAP"
	_Protocol_name_4 = "GMTPIFMPPNNIPIMARISSCPSQNXAIPCOMPSNPCOMPAQ_PEERIPX_IN_IPVRRPPGM"
	_Protocol_name_5 = "L2TPDDXIATPSTPSRPUTISMPSMPTPISISFIRECRTPCRUDPSSCOPMCEIPLTSPSPIPESCTPFCRSVP_E2E_IGNOREMOBILITYUDP_LITEMPLS_IN_IP"
	_Protocol_name_6 = "RESERVED"
)

var (
	_Protocol_index_0 = [...]uint16{0, 22, 26, 30, 33, 41, 43, 46, 49, 52, 55, 66, 72, 75, 80, 85, 89, 94, 97, 100, 108, 111, 114, 121, 128, 135, 141, 147, 150, 154, 161, 167, 174, 183, 186, 190, 194, 197, 200, 209, 211, 213, 222, 226, 236, 254, 258, 262, 265, 269, 272, 281, 289, 295, 300, 304, 310, 314, 318, 323, 332, 355}
	_Protocol_index_1 = [...]uint8{0, 4}
	_Protocol_index_2 = [...]uint8{0, 9, 18, 21, 25}
	_Protocol_index_3 = [...]uint8{0, 7, 11, 15, 19, 23, 26, 29, 39, 45, 51, 59, 65, 69, 80, 85, 88, 98, 101, 104, 109, 113, 123, 127, 130, 132, 136, 140, 146, 153, 158}
	_Protocol_index_4 = [...]uint8{0, 4, 8, 12, 15, 19, 23, 26, 27, 33, 36, 47, 56, 60, 63}
	_Protocol_index_5 = [...]uint8{0, 4, 7, 11, 14, 17, 20, 23, 25, 28, 32, 36, 40, 45, 53, 57, 60, 64, 68, 70, 85, 93, 101, 111}
	_Protocol_index_6 = [...]uint8{0, 8}
)

func (i Protocol) String() string {
	switch {
	case 0 <= i && i <= 60:
		return _Protocol_name_0[_Protocol_index_0[i]:_Protocol_index_0[i+1]]
	case i == 62:
		return _Protocol_name_1
	case 64 <= i && i <= 67:
		i -= 64
		return _Protocol_name_2[_Protocol_index_2[i]:_Protocol_index_2[i+1]]
	case 69 <= i && i <= 98:
		i -= 69
		return _Protocol_name_3[_Protocol_index_3[i]:_Protocol_index_3[i+1]]
	case 100 <= i && i <= 113:
		i -= 100
		return _Protocol_name_4[_Protocol_index_4[i]:_Protocol_index_4[i+1]]
	case 115 <= i && i <= 137:
		i -= 115
		return _Protocol_name_5[_Protocol_index_5[i]:_Protocol_index_5[i+1]]
	case i == 255:
		return _Protocol_name_6
	default:
		return fmt.Sprintf("Protocol(%d)", i)
	}
}
