// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=tuntap -id ifPool -d PoolType=ifPool -d Type=Interface -d Data=elts github.com/platinasystems/elib/pool.tmpl]

package tuntap

import (
	"github.com/platinasystems/elib"
)

type ifPool struct {
	elib.Pool
	elts []Interface
}

func (p *ifPool) GetIndex() (i uint) {
	l := uint(len(p.elts))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *ifPool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *ifPool) IsFree(i uint) (v bool) {
	v = i >= uint(len(p.elts))
	if !v {
		v = p.Pool.IsFree(i)
	}
	return
}

func (p *ifPool) Resize(n uint) {
	c := elib.Index(cap(p.elts))
	l := elib.Index(len(p.elts) + int(n))
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Interface, l, c)
		copy(q, p.elts)
		p.elts = q
	}
	p.elts = p.elts[:l]
}

func (p *ifPool) Validate(i uint) {
	c := elib.Index(cap(p.elts))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Interface, l, c)
		copy(q, p.elts)
		p.elts = q
	}
	if l > elib.Index(len(p.elts)) {
		p.elts = p.elts[:l]
	}
}

func (p *ifPool) Elts() uint {
	return uint(len(p.elts)) - p.FreeLen()
}

func (p *ifPool) Len() uint {
	return uint(len(p.elts))
}

func (p *ifPool) Foreach(f func(x Interface)) {
	for i := range p.elts {
		if !p.Pool.IsFree(uint(i)) {
			f(p.elts[i])
		}
	}
}
