// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=tuntap -id iovec -d VecType=iovecVec -d Type=iovec github.com/platinasystems/elib/vec.tmpl]

package tuntap

import (
	"github.com/platinasystems/elib"
)

type iovecVec []iovec

func (p *iovecVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]iovec, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *iovecVec) validate(i uint, zero *iovec) *iovec {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]iovec, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *iovecVec) Validate(i uint) *iovec                 { return p.validate(i, (*iovec)(nil)) }
func (p *iovecVec) ValidateInit(i uint, zero iovec) *iovec { return p.validate(i, &zero) }

func (p iovecVec) Len() uint { return uint(len(p)) }
