// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=tuntap -id ifVec -d VecType=interfaceVec -d Type=*Interface github.com/platinasystems/elib/vec.tmpl]

package tuntap

import (
	"github.com/platinasystems/elib"
)

type interfaceVec []*Interface

func (p *interfaceVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Interface, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *interfaceVec) validate(i uint, zero **Interface) **Interface {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*Interface, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}
func (p *interfaceVec) Validate(i uint) **Interface                      { return p.validate(i, (**Interface)(nil)) }
func (p *interfaceVec) ValidateInit(i uint, zero *Interface) **Interface { return p.validate(i, &zero) }

func (p interfaceVec) Len() uint { return uint(len(p)) }
