// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id FibAddDelHook -d Package=ip4 -d DepsType=FibAddDelHookVec -d Type=FibAddDelHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package ip4

import (
	"github.com/platinasystems/elib/dep"
)

type FibAddDelHookVec struct {
	deps  dep.Deps
	hooks []FibAddDelHook
}

func (t *FibAddDelHookVec) Len() int {
	return t.deps.Len()
}

func (t *FibAddDelHookVec) Get(i int) FibAddDelHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *FibAddDelHookVec) Add(x FibAddDelHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
