// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id FibSetUnsetHook -d Package=ip4 -d DepsType=FibSetUnsetHookVec -d Type=FibSetUnsetHook -d Data=hooks github.com/platinasystems/elib/dep/dep.tmpl]

package ip4

import (
	"github.com/platinasystems/elib/dep"
)

type FibSetUnsetHookVec struct {
	deps  dep.Deps
	hooks []FibSetUnsetHook
}

func (t *FibSetUnsetHookVec) Len() int {
	return t.deps.Len()
}

func (t *FibSetUnsetHookVec) Get(i int) FibSetUnsetHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *FibSetUnsetHookVec) Add(x FibSetUnsetHook, ds ...*dep.Dep) {
	for i := range ds {
		t.deps.Add(ds[i])
	}
	t.hooks = append(t.hooks, x)
}
