// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip4 -id Fib -d VecType=FibVec -d Type=*Fib github.com/platinasystems/elib/vec.tmpl]

package ip4

import (
	"github.com/platinasystems/elib"
)

type FibVec []*Fib

func (p *FibVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Fib, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *FibVec) Validate(i uint) **Fib {
	c := elib.Index(cap(*p))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Fib, l, c)
		copy(q, *p)
		*p = q
	}
	if l > elib.Index(len(*p)) {
		*p = (*p)[:l]
	}
	return &(*p)[i]
}

func (p FibVec) Len() uint { return uint(len(p)) }
